// Compiles docs/project_atlas/data/*.json into atlas-data.js so the atlas
// works when opened straight from disk (no fetch, no server). Run: npm run atlas
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const atlasDir = path.join(repoRoot, "docs", "project_atlas");
const dataDir = path.join(atlasDir, "data");

const bundle = {};
for (const file of fs.readdirSync(dataDir).filter((f) => f.endsWith(".json"))) {
  const key = path.basename(file, ".json").replace(/[^a-z0-9]+/gi, "_");
  bundle[key] = JSON.parse(fs.readFileSync(path.join(dataDir, file), "utf8"));
}

const out = `// GENERATED by scripts/build-atlas.mjs — edit data/*.json, not this file.\nwindow.ATLAS_DATA = ${JSON.stringify(bundle, null, 2)};\n`;
fs.writeFileSync(path.join(atlasDir, "atlas-data.js"), out, "utf8");
console.log(`wrote ${path.join(atlasDir, "atlas-data.js")} (${Object.keys(bundle).join(", ")})`);
